CREATE SCHEMA DS;

CREATE SCHEMA LOGS;

CREATE TABLE DS.FT_BALANCE_F (
    ON_DATE DATE NOT NULL,
    ACCOUNT_RK INTEGER NOT NULL,
    CURRENCY_RK INTEGER NOT NULL,
    BALANCE_OUT FLOAT,
    PRIMARY KEY (ON_DATE, ACCOUNT_RK)
);

CREATE TABLE DS.FT_POSTING_F (
    OPER_DATE DATE NOT NULL,
    CREDIT_ACCOUNT_RK INTEGER NOT NULL,
    DEBET_ACCOUNT_RK INTEGER NOT NULL,
    CREDIT_AMOUNT FLOAT NOT NULL,
    DEBET_AMOUNT FLOAT NOT NULL
);

CREATE TABLE DS.MD_ACCOUNT_D (
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE NOT NULL,
    ACCOUNT_RK INTEGER NOT NULL,
    ACCOUNT_NUMBER VARCHAR(20) NOT NULL,
    CHAR_TYPE VARCHAR(1) NOT NULL,
    CURRENCY_RK INTEGER NOT NULL,
    CURRENCY_CODE VARCHAR(3) NOT NULL,
    PRIMARY KEY (DATA_ACTUAL_DATE, ACCOUNT_RK)
);

CREATE TABLE DS.MD_CURRENCY_D (
    CURRENCY_RK INTEGER NOT NULL,
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_CODE VARCHAR(3),
    CODE_ISO_CHAR VARCHAR(3),
    PRIMARY KEY (CURRENCY_RK, DATA_ACTUAL_DATE)
);

CREATE TABLE DS.MD_EXCHANGE_RATE_D (
    DATA_ACTUAL_DATE DATE NOT NULL,
    DATA_ACTUAL_END_DATE DATE,
    CURRENCY_RK INTEGER NOT NULL,
    REDUCED_COURCE FLOAT,
    CODE_ISO_NUM VARCHAR(3),
    PRIMARY KEY (DATA_ACTUAL_DATE, CURRENCY_RK)
);

CREATE TABLE DS.MD_LEDGER_ACCOUNT_S (
    CHAPTER CHAR(1),
    CHAPTER_NAME VARCHAR(16),
    SECTION_NUMBER INTEGER,
    SECTION_NAME VARCHAR(22),
    SUBSECTION_NAME VARCHAR(21),
    LEDGER1_ACCOUNT INTEGER,
    LEDGER1_ACCOUNT_NAME VARCHAR(47),
    LEDGER_ACCOUNT INTEGER NOT NULL,
    LEDGER_ACCOUNT_NAME VARCHAR(153),
    CHARACTERISTIC CHAR(1),
    IS_RESIDENT INTEGER,
    IS_RESERVE INTEGER,
    IS_RESERVED INTEGER,
    IS_LOAN INTEGER,
    IS_RESERVED_ASSETS INTEGER,
    IS_OVERDUE INTEGER,
    IS_INTEREST INTEGER,
    PAIR_ACCOUNT VARCHAR(5),
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    IS_RUB_ONLY INTEGER,
    MIN_TERM VARCHAR(1),
    MIN_TERM_MEASURE VARCHAR(1),
    MAX_TERM VARCHAR(1),
    MAX_TERM_MEASURE VARCHAR(1),
    LEDGER_ACC_FULL_NAME_TRANSLIT VARCHAR(1),
    IS_REVALUATION VARCHAR(1),
    IS_CORRECT VARCHAR(1),
    PRIMARY KEY (LEDGER_ACCOUNT, START_DATE)
);

CREATE TABLE LOGS.LOAD_LOG (
    LOG_ID SERIAL PRIMARY KEY,
    PROCESS_NAME VARCHAR(100) NOT NULL,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    COMMENT TEXT
);