CREATE SCHEMA DM;

CREATE TABLE DM.DM_ACCOUNT_TURNOVER_F(
    ON_DATE DATE,
    ACCOUNT_RK NUMERIC(23,8),
    CREDIT_AMOUNT NUMERIC(23,8),
    CREDIT_AMOUNT_RUB NUMERIC(23,8),
    DEBET_AMOUNT NUMERIC(23,8),
    DEBET_AMOUNT_RUB NUMERIC(23,8)
);

CREATE TABLE DM.DM_ACCOUNT_BALANCE_F(
    ON_DATE DATE,
    ACCOUNT_RK NUMERIC(23,8),
    BALANCE_OUT FLOAT,
    BALANCE_OUT_RUB FLOAT
);


INSERT INTO DM.DM_ACCOUNT_BALANCE_F (
    ON_DATE,
    ACCOUNT_RK,
    BALANCE_OUT,
    BALANCE_OUT_RUB
)
SELECT
    BF.ON_DATE,
    BF.ACCOUNT_RK,
    BF.BALANCE_OUT,
    BF.BALANCE_OUT * COALESCE(ER.REDUCED_COURCE, 1) AS BALANCE_OUT_RUB
FROM DS.FT_BALANCE_F BF
         LEFT JOIN DS.MD_EXCHANGE_RATE_D ER
                   ON BF.CURRENCY_RK = ER.CURRENCY_RK AND BF.ON_DATE BETWEEN ER.DATA_ACTUAL_DATE AND ER.DATA_ACTUAL_END_DATE
WHERE BF.ON_DATE = '2017-12-31';

