CREATE OR REPLACE PROCEDURE DM.RUN_SCRIPT(DATE_START DATE, DATE_END DATE)
AS $$
DECLARE
    I_ONDATE DATE;
BEGIN
    FOR I_ONDATE IN (SELECT * FROM GENERATE_SERIES(DATE_START, DATE_END, '1 DAY') S(I_ONDATE)) LOOP
            CALL DM.FILL_ACCOUNT_BALANCE_F(I_ONDATE);
            CALL DM.FILL_ACCOUNT_TURNOVER_F(I_ONDATE);
        END LOOP;
END;
$$ LANGUAGE PLPGSQL;

CALL DM.RUN_SCRIPT('2018-01-01', '2018-01-31');
